import { AccordionItem } from '../models/AccordionItem'

export const Data: AccordionItem[] = [
  {
    name: 'Africa',
    countries: [
      'Algeria',
      'Benin',
      'Botswana',
      'Burkina Faso',
      'Burundi',
      'Cameroon',
      'Cape Verde',
      'Central African Republic',
      'Chad',
      'Comoros',
      'Congo',
      "Cote d'Ivoire",
      'Democratic Congo',
      'Djibouti',
      'Egypt',
      'Equatorial Guinea',
      'Eritrea',
      'Ethiopia',
      'Gabon',
      'Gambia',
      'Ghana',
      'Guinea',
      'Guinea-Bissau',
      'Kenya',
      'Lesotho',
      'Liberia',
      'Libyan Arab Jamahiriya',
      'Madagascar',
      'Malawi',
      'Mali',
      'Mauritania',
      'Mauritius',
      'Mayotte',
      'Morocco',
      'Mozambique',
      'Namibia',
      'Niger',
      'Nigeria',
      'Reunion',
      'Rwanda',
      'Saint Helena',
      'Sao Tome and Principe',
      'Senegal',
      'Seychelles',
      'Sierra Leone',
      'Somalia',
      'South Africa',
      'South Sudan',
      'Sudan',
      'Swaziland',
      'Tanzania',
      'Togo',
      'Tunisia',
      'Uganda',
      'Western Sahara',
      'Zambia',
      'Zimbabwe',
    ],
  },
  {
    name: 'Antartica',
    countries: [
      'Antarctica',
      'Bouvet Island',
      'French Southern Territories',
      'Heard Island and McDonald Islands',
      'South Georgia and the South Sandwich Islands',
    ],
  },
  {
    name: 'Asia',
    countries: [
      'Afghanistan',
      'Armenia',
      'Azerbaijan',
      'Bahrain',
      'Bangladesh',
      'Bhutan',
      'British Indian Ocean Territory',
      'Brunei Darussalam',
      'Cambodia',
      'China',
      'Christmas Island',
      'Cocos (Keeling) Islands',
      'Cyprus',
      'Georgia',
      'Hong Kong',
      'India',
      'Indonesia',
      'Iran',
      'Iraq',
      'Israel',
      'Japan',
      'Jordan',
      'Kazakhstan',
      'Korea',
      'Democratic Korea',
      'Korea',
      'Kuwait',
      'Kyrgyz',
      "Lao People's Democratic Republic",
      'Lebanon',
      'Macao',
      'Malaysia',
      'Maldives',
      'Mongolia',
      'Myanmar',
      'Nepal',
      'Oman',
      'Pakistan',
      'Palestinian Territory',
      'Philippines',
      'Qatar',
      'Russian Federation',
      'Saudi Arabia',
      'Singapore',
      'Sri Lanka',
      'Syrian Arab Republic',
      'Taiwan',
      'Tajikistan',
      'Thailand',
      'Timor-Leste',
      'Turkey',
      'Turkmenistan',
      'United Arab Emirates',
      'Uzbekistan',
      'Vietnam',
      'Yemen',
    ],
  },
  {
    name: 'Australia',
    countries: [
      'American Samoa',
      'Australia',
      'Cook Islands',
      'Fiji',
      'French Polynesia',
      'Guam',
      'Kiribati',
      'Marshall Islands',
      'Micronesia',
      'Nauru',
      'New Caledonia',
      'New Zealand',
      'Niue',
      'Norfolk Island',
      'Northern Mariana Islands',
      'Palau',
      'Papua New Guinea',
      'Pitcairn Islands',
      'Samoa',
      'Solomon Islands',
      'Tokelau',
      'Tonga',
      'Tuvalu',
      'United States Minor Outlying Islands',
      'Vanuatu',
      'Wallis and Futuna',
    ],
  },
  {
    name: 'Europe',
    countries: [
      'Albania',
      'Andorra',
      'Armenia',
      'Austria',
      'Azerbaijan',
      'Bosnia and Herzegovina',
      'Bulgaria',
      'Croatia',
      'Cyprus',
      'Czech Republic',
      'Denmark',
      'Estonia',
      'Faroe Islands',
      'Finland',
      'France',
      'Georgia',
      'Germany',
      'Gibraltar',
      'Greece',
      'Guernsey',
      'Holy See',
      'Iceland',
      'Ireland',
      'Isle of Man',
      'Italy',
      'Jersey',
      'Kazakhstan',
      'Latvia',
      'Liechtenstein',
      'Lithuania',
      'Luxembourg',
      'Macedonia',
      'Malta',
      'Moldova',
      'Monaco',
      'Montenegro',
      'Netherlands',
      'Norway',
      'Poland',
      'Portugal',
      'Russian Federation',
      'San Marino',
      'Serbia',
      'Slovakia',
      'Slovenia',
      'Spain',
      'Svalbard & Jan Mayen Islands',
      'Sweden',
      'Switzerland',
      'Turkey',
      'Ukraine',
      'United Kingdom of Great Britain & Northern Ireland',
      'Ã…land Islands',
      'Albania',
    ],
  },
  {
    name: 'North America',
    countries: [
      'Anguilla',
      'Antigua and Barbuda',
      'Aruba',
      'Bahamas',
      'Barbados',
      'Belize',
      'Bermuda',
      'Bonaire',
      'British Virgin Islands',
      'Canada',
      'Cayman Islands',
      'Costa Rica',
      'Cuba',
      'CuraÃ§ao',
      'Dominica',
      'Dominican Republic',
      'El Salvador',
      'Greenland',
      'Grenada',
      'Guadeloupe',
      'Guatemala',
      'Haiti',
      'Honduras',
      'Jamaica',
      'Martinique',
      'Mexico',
      'Montserrat',
      'Netherlands Antilles',
      'Nicaragua',
      'Panama',
      'Puerto Rico',
      'Saint Barthelemy',
      'Saint Kitts and Nevis',
      '"Saint Lucia',
      'Saint Martin',
      'Saint Pierre and Miquelon',
      'Saint Vincent and the Grenadines',
      'Sint Maarten (Netherlands)',
      'Trinidad and Tobago',
      'Turks and Caicos Islands',
      'United States Minor Outlying Islands',
      'United States Virgin Islands',
      'United States of America',
    ],
  },
  {
    name: 'South America',
    countries: [
      'Argentina',
      'Bolivia',
      'Brazil',
      'Colombia',
      'Ecuador',
      'Falkland Islands',
      'French Guiana',
      'Guyana',
      'Paraguay',
      'Peru',
      'Suriname',
      'Uruguay',
      'Venezuela',
    ],
  },
]
